### ISSUE TITLE
/jainfo doesn't work sometimes for snitches with logs

### ISSUE THREAD

**Issue by awoo-civ** [DevotedMC/JukeAlert#23]
Certain snitches appear to get bugged, they only respond to /jainfo requests for pages without logs.

I can't reproduce it, snitches appear to get affected randomly, and stay bugged until replaced.

**Comment by ProgrammerDan** [comment]
Is this still true or fixed by recent merge?

**Comment by awoo-civ** [comment]
Not sure, possibly fixed. Hard to tell as it was difficult to reproduce.

I believe that the bugged snitches did have rather long names so I'll just assume that https://github.com/DevotedMC/JukeAlert/pull/27 fixed this and close this issue. I'll reopen if I see it happen again.
