### ISSUE TITLE
Add hover info to messages

### ISSUE THREAD

**Issue by awoo-civ** [DevotedMC/JukeAlert#24]
- [x] /jalist - https://github.com/Civcraft/JukeAlert/pull/77
- [x] /janame - https://github.com/DevotedMC/JukeAlert/pull/12
- [x] /jainfo - https://github.com/DevotedMC/JukeAlert/pull/36
- [x] Snitch placement - https://github.com/DevotedMC/JukeAlert/pull/15 
- [x] Snitch notification - https://github.com/DevotedMC/JukeAlert/pull/36
- [x] /jaclear - https://github.com/DevotedMC/JukeAlert/pull/36
- [x] /jalookup - https://github.com/DevotedMC/JukeAlert/pull/36
- [x] Snitch destruction - https://github.com/DevotedMC/JukeAlert/issues/34 https://github.com/DevotedMC/JukeAlert/pull/37

Information to show:
 - World name
 - Coordinates
 - Group
 - Previous name (only /janame)
 - Name
 - Cull time
 - Type (Juke/Note)

Potential additions:
 - Reinforcement type
 - Date of placement

**Comment by ProgrammerDan** [comment]
Any more progress onthis? Had some additional requests for it

**Comment by awoo-civ** [comment]
@Gjum said he was gonna do it. Any day now ;)
