### ISSUE TITLE
From Gjum: Some snitch entries do not have item representation in /ja GUI

### ISSUE THREAD

**Issue by ProgrammerDan** [DevotedMC/JukeAlert#28]
I'll direct Gjum here to add more details

**Comment by Gjum** [comment]
some block types aren't visible in inventory guis, for example crops

when setting the item type to these blocks, the items will be treated as empty slots by the gui

a solution would be to display a different item instead

![/ja gui with missing items for crop breaks](https://cdn.discordapp.com/attachments/227537787392360449/307256096895270913/2017-04-27-224350_333x226_scrot.png)

![/jainfo output](https://cdn.discordapp.com/attachments/227537787392360449/307256089471090690/2017-04-27-224519_407x253_scrot.png)

**Comment by GavJenks** [comment]
Also getting a few players complaining about this:
![image](https://user-images.githubusercontent.com/1256888/64574029-8f6aca00-d322-11e9-90fe-3e88a946b852.png)

**Comment by GavJenks** [comment]
They said that it even varied by the individual type of flower broken? Maybe it's "blocks introduced since whenever this was first coded" because something is badly hard coded somewhere?

**Comment by Gjum** [comment]
the [code](https://github.com/DevotedMC/JukeAlert/blob/29daed8/src/main/java/com/untamedears/JukeAlert/gui/SnitchLogGUI.java#L166) just calls `new ItemStack(action.getMaterial())` which I guess returns an item stack with an invalid item (can't get rendered) in the case of certain blocks. this seems to be the place where this could be fixed.

**Comment by ProgrammerDan** [comment]
Resolved by #66
