### ISSUE TITLE
Allow players to run /jalookup regardless of permissions

### ISSUE THREAD

**Issue by awoo-civ** [DevotedMC/JukeAlert#35]
I think you should always be able to find out what group a snitch you see a notification from is on.

This would involve removing the LOOKUP_SNITCH permission.

At the very least, Members should have the permission granted by default.

**Comment by ProgrammerDan** [comment]
Only issue I can see is then adding people to check a single snitch is equivalent to telling them where your whole network is.

**Comment by Gjum** [comment]
I don't see why that permission would need to be removed. looking up a snitch's group (or getting it from an alert) isn't the same as looking up all group's snitches.

**Comment by awoo-civ** [comment]
I guess technically someone *could* /jalookup every single coordinate or something yea.

Then I propose adding the permission to Members by default. Players commonly add others to their snitch groups as Members without thinking about the permission.

**Comment by awoo-civ** [comment]
Actually, I don't see a use case for this anymore as https://github.com/DevotedMC/JukeAlert/pull/36 adds group information to notifications.
