### ISSUE TITLE
Add a mass-rename command

### ISSUE THREAD

**Issue by awoo-civ** [DevotedMC/JukeAlert#48]
By @Ameliorate https://www.reddit.com/r/civclassics/comments/6lt7cs/changelog_for_772017/djxf84f/

> I've been thinking of implementing a mass-rename command in JukeAlert that renames any snitch with a given pattern in it's name, even if you aren't near it.
`/jamassrename [GROUP] [REGEX] [REPLACE]`
For example, `/jamassrename IllegalSnitchNetwork ^\[ISN] [LegalSN]` would rename `[ISN]ZeroZero` to `[LegalSN]ZeroZero`.
Is this something I should put effort into?
I might implement a separate mode to use textual replace instead of a regex, but that's mostly an implementation detail.

This feature would absolutely have to support undo functionality.

**Comment by ProgrammerDan** [comment]
Decent QOL feature, I'd love to see it in connection with a command block for snitch networks as has been previously spec'd; basically, connect this with that, you can mass rename via the "master" control block.

No idea if there is further interest in better C&C and snitch discovery, though

**Comment by awoo-civ** [comment]
A naive but easy implementation would be a simple `/jarename <world> <x> <y> <z>` that lets you rename a single snitch. Then it'd be up to the players to write macros that rename groups of snitches.
