### ISSUE TITLE
Feature: Blacklist instead of whitelist jukes

### ISSUE THREAD

**Issue by GavJenks** [DevotedMC/JukeAlert#49]
Can't believe this doesn't seem to be on the issue list??? Simple: jukes currently record people who aren't on a list. There should also be an option to record people who ARE on a list only. Important for traps, or for a very high traffic area where you only want the snitch network to look for some raider group that's been causing problems, etc. etc.

**Comment by ProgrammerDan** [comment]
AFAIK this is handled by clever use of the NameLayer blacklists. Jukes themselves just record -- what they record, who they record, is controlled by NameLayer, not JukeAlert (weird as that sounds).

How to accomplish: Add targeted individuals to the BLACKLIST of a group. For NOT_BLACKLIST permission node, and all other "normal" permission types, grant SNITCH_IMMUNE.  Now, those jukes will _only_ trigger for the targetted persons.

**Comment by GavJenks** [comment]
Gotcha thanks!
